name: CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter --version
      - run: flutter test

  build-ios:
    needs: test
    runs-on: macos-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - uses: actions/upload-artifact@v3
        with:
          path: RewardProcessing/build/ios/iphoneos/Runner.app
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: RewardProcessing/build/ios/iphoneos/Runner.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-android:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle --release
      - uses: actions/upload-artifact@v3
        with:
          path: RewardProcessing/build/app/outputs/flutter-apk/app-release.apk
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: RewardProcessing/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}