name: CI

on:
  pull_request:
    branches: [ "main" ]
jobs:
  lint-analyse:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze

  flutter-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: flutter --version

  # Android
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle

  # iOS
  build-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: RewardProcessing
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ios --release --no-codesign